name: Knit R Markdown

on:
  push:
  branches:
  - main

jobs:
  knit:
  runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
uses: actions/checkout@v4

- name: Set up R
uses: r-lib/actions/setup-r@v2
with:
  r-version: '4.3.0' # Specify R version

- name: Install R Dependencies
uses: r-lib/actions/setup-r-dependencies@v2
with:
  packages: |
  any::rmarkdown
  any::knitr
  any::tidyverse
  any::tidymodels
  any::reactable
  any::htmltools
# Add other packages used in your .Rmd

- name: Knit Rmd to HTML
run: |
  Rscript -e "rmarkdown::render('report.Rmd', output_file = 'report.html')"
shell: bash

- name: Commit Rendered Output
run: |
  git config --local user.email "github-actions[bot]@users.noreply.github.com"
git config --local user.name "github-actions[bot]"
git add report.html
git commit -m "Auto-knit report.Rmd to HTML" || echo "No changes to commit"
git push
env:

  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
